package com.venta.sistema.core.model;
// Generated Jan 3, 2017 5:45:21 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private int id;
     private Familia familia;
     private String descripcion;
     private String nombre;
     private Date caduceEn;
     private BigDecimal precio;
     private Date actualizadoEn;
     private String actualizadoPor;
     private boolean estado;
     private Set facturaDetalles = new HashSet(0);
     private Set inventarios = new HashSet(0);

    public Articulo() {
    }

	
    public Articulo(int id, Familia familia, String descripcion, String nombre, Date caduceEn, BigDecimal precio, Date actualizadoEn, String actualizadoPor, boolean estado) {
        this.id = id;
        this.familia = familia;
        this.descripcion = descripcion;
        this.nombre = nombre;
        this.caduceEn = caduceEn;
        this.precio = precio;
        this.actualizadoEn = actualizadoEn;
        this.actualizadoPor = actualizadoPor;
        this.estado = estado;
    }
    public Articulo(int id, Familia familia, String descripcion, String nombre, Date caduceEn, BigDecimal precio, Date actualizadoEn, String actualizadoPor, boolean estado, Set facturaDetalles, Set inventarios) {
       this.id = id;
       this.familia = familia;
       this.descripcion = descripcion;
       this.nombre = nombre;
       this.caduceEn = caduceEn;
       this.precio = precio;
       this.actualizadoEn = actualizadoEn;
       this.actualizadoPor = actualizadoPor;
       this.estado = estado;
       this.facturaDetalles = facturaDetalles;
       this.inventarios = inventarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Familia getFamilia() {
        return this.familia;
    }
    
    public void setFamilia(Familia familia) {
        this.familia = familia;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getCaduceEn() {
        return this.caduceEn;
    }
    
    public void setCaduceEn(Date caduceEn) {
        this.caduceEn = caduceEn;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Date getActualizadoEn() {
        return this.actualizadoEn;
    }
    
    public void setActualizadoEn(Date actualizadoEn) {
        this.actualizadoEn = actualizadoEn;
    }
    public String getActualizadoPor() {
        return this.actualizadoPor;
    }
    
    public void setActualizadoPor(String actualizadoPor) {
        this.actualizadoPor = actualizadoPor;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public Set getFacturaDetalles() {
        return this.facturaDetalles;
    }
    
    public void setFacturaDetalles(Set facturaDetalles) {
        this.facturaDetalles = facturaDetalles;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }




}


