package com.venta.sistema.core.model;
// Generated Jan 3, 2017 5:45:21 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FacturaDetalle generated by hbm2java
 */
public class FacturaDetalle  implements java.io.Serializable {


     private int id;
     private Articulo articulo;
     private Factura factura;
     private Date actualizadoEn;
     private String actualizadoPor;

    public FacturaDetalle() {
    }

    public FacturaDetalle(int id, Articulo articulo, Factura factura, Date actualizadoEn, String actualizadoPor) {
       this.id = id;
       this.articulo = articulo;
       this.factura = factura;
       this.actualizadoEn = actualizadoEn;
       this.actualizadoPor = actualizadoPor;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Date getActualizadoEn() {
        return this.actualizadoEn;
    }
    
    public void setActualizadoEn(Date actualizadoEn) {
        this.actualizadoEn = actualizadoEn;
    }
    public String getActualizadoPor() {
        return this.actualizadoPor;
    }
    
    public void setActualizadoPor(String actualizadoPor) {
        this.actualizadoPor = actualizadoPor;
    }




}


