package com.venta.sistema.core.model;
// Generated Jan 3, 2017 5:45:21 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PermisoUsuario generated by hbm2java
 */
public class PermisoUsuario  implements java.io.Serializable {


     private int id;
     private Usuarios usuarios;
     private Permisos permisos;
     private Date actualizadoEn;
     private String actualizadoPor;

    public PermisoUsuario() {
    }

    public PermisoUsuario(int id, Usuarios usuarios, Permisos permisos, Date actualizadoEn, String actualizadoPor) {
       this.id = id;
       this.usuarios = usuarios;
       this.permisos = permisos;
       this.actualizadoEn = actualizadoEn;
       this.actualizadoPor = actualizadoPor;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Permisos getPermisos() {
        return this.permisos;
    }
    
    public void setPermisos(Permisos permisos) {
        this.permisos = permisos;
    }
    public Date getActualizadoEn() {
        return this.actualizadoEn;
    }
    
    public void setActualizadoEn(Date actualizadoEn) {
        this.actualizadoEn = actualizadoEn;
    }
    public String getActualizadoPor() {
        return this.actualizadoPor;
    }
    
    public void setActualizadoPor(String actualizadoPor) {
        this.actualizadoPor = actualizadoPor;
    }




}


