package com.venta.sistema.core.model;
// Generated Jan 3, 2017 5:45:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Permisos generated by hbm2java
 */
public class Permisos  implements java.io.Serializable {


     private int id;
     private String descripcion;
     private char abrev;
     private Date actualizadoEn;
     private String actualizadoPor;
     private Set permisoUsuarios = new HashSet(0);

    public Permisos() {
    }

	
    public Permisos(int id, String descripcion, char abrev, Date actualizadoEn, String actualizadoPor) {
        this.id = id;
        this.descripcion = descripcion;
        this.abrev = abrev;
        this.actualizadoEn = actualizadoEn;
        this.actualizadoPor = actualizadoPor;
    }
    public Permisos(int id, String descripcion, char abrev, Date actualizadoEn, String actualizadoPor, Set permisoUsuarios) {
       this.id = id;
       this.descripcion = descripcion;
       this.abrev = abrev;
       this.actualizadoEn = actualizadoEn;
       this.actualizadoPor = actualizadoPor;
       this.permisoUsuarios = permisoUsuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public char getAbrev() {
        return this.abrev;
    }
    
    public void setAbrev(char abrev) {
        this.abrev = abrev;
    }
    public Date getActualizadoEn() {
        return this.actualizadoEn;
    }
    
    public void setActualizadoEn(Date actualizadoEn) {
        this.actualizadoEn = actualizadoEn;
    }
    public String getActualizadoPor() {
        return this.actualizadoPor;
    }
    
    public void setActualizadoPor(String actualizadoPor) {
        this.actualizadoPor = actualizadoPor;
    }
    public Set getPermisoUsuarios() {
        return this.permisoUsuarios;
    }
    
    public void setPermisoUsuarios(Set permisoUsuarios) {
        this.permisoUsuarios = permisoUsuarios;
    }




}


