package com.venta.sistema.core.model;
// Generated Jan 3, 2017 5:45:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int id;
     private Dni dni;
     private Sexo sexo;
     private Nacionalidad nacionalidad;
     private EstadoCivil estadoCivil;
     private String nombre;
     private String apellido;
     private Date fechaNacimiento;
     private Date actualizadoEn;
     private String actualizadoPor;
     private Set facturasForDespachadoPor = new HashSet(0);
     private Set facturasForClienteId = new HashSet(0);
     private Set usuarioses = new HashSet(0);

    public Persona() {
    }

	
    public Persona(int id, Dni dni, Sexo sexo, Nacionalidad nacionalidad, EstadoCivil estadoCivil, String nombre, String apellido, Date fechaNacimiento, Date actualizadoEn, String actualizadoPor) {
        this.id = id;
        this.dni = dni;
        this.sexo = sexo;
        this.nacionalidad = nacionalidad;
        this.estadoCivil = estadoCivil;
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaNacimiento = fechaNacimiento;
        this.actualizadoEn = actualizadoEn;
        this.actualizadoPor = actualizadoPor;
    }
    public Persona(int id, Dni dni, Sexo sexo, Nacionalidad nacionalidad, EstadoCivil estadoCivil, String nombre, String apellido, Date fechaNacimiento, Date actualizadoEn, String actualizadoPor, Set facturasForDespachadoPor, Set facturasForClienteId, Set usuarioses) {
       this.id = id;
       this.dni = dni;
       this.sexo = sexo;
       this.nacionalidad = nacionalidad;
       this.estadoCivil = estadoCivil;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNacimiento = fechaNacimiento;
       this.actualizadoEn = actualizadoEn;
       this.actualizadoPor = actualizadoPor;
       this.facturasForDespachadoPor = facturasForDespachadoPor;
       this.facturasForClienteId = facturasForClienteId;
       this.usuarioses = usuarioses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Dni getDni() {
        return this.dni;
    }
    
    public void setDni(Dni dni) {
        this.dni = dni;
    }
    public Sexo getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Sexo sexo) {
        this.sexo = sexo;
    }
    public Nacionalidad getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(Nacionalidad nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public EstadoCivil getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(EstadoCivil estadoCivil) {
        this.estadoCivil = estadoCivil;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Date getActualizadoEn() {
        return this.actualizadoEn;
    }
    
    public void setActualizadoEn(Date actualizadoEn) {
        this.actualizadoEn = actualizadoEn;
    }
    public String getActualizadoPor() {
        return this.actualizadoPor;
    }
    
    public void setActualizadoPor(String actualizadoPor) {
        this.actualizadoPor = actualizadoPor;
    }
    public Set getFacturasForDespachadoPor() {
        return this.facturasForDespachadoPor;
    }
    
    public void setFacturasForDespachadoPor(Set facturasForDespachadoPor) {
        this.facturasForDespachadoPor = facturasForDespachadoPor;
    }
    public Set getFacturasForClienteId() {
        return this.facturasForClienteId;
    }
    
    public void setFacturasForClienteId(Set facturasForClienteId) {
        this.facturasForClienteId = facturasForClienteId;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }




}


