package com.venta.sistema.core.model;
// Generated Jan 3, 2017 5:45:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int id;
     private Persona persona;
     private String usuario;
     private Date actualizadoEn;
     private String actualizadoPor;
     private boolean estado;
     private String contrasena;
     private Set permisoUsuarios = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(int id, Persona persona, String usuario, Date actualizadoEn, String actualizadoPor, boolean estado, String contrasena) {
        this.id = id;
        this.persona = persona;
        this.usuario = usuario;
        this.actualizadoEn = actualizadoEn;
        this.actualizadoPor = actualizadoPor;
        this.estado = estado;
        this.contrasena = contrasena;
    }
    public Usuarios(int id, Persona persona, String usuario, Date actualizadoEn, String actualizadoPor, boolean estado, String contrasena, Set permisoUsuarios) {
       this.id = id;
       this.persona = persona;
       this.usuario = usuario;
       this.actualizadoEn = actualizadoEn;
       this.actualizadoPor = actualizadoPor;
       this.estado = estado;
       this.contrasena = contrasena;
       this.permisoUsuarios = permisoUsuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getActualizadoEn() {
        return this.actualizadoEn;
    }
    
    public void setActualizadoEn(Date actualizadoEn) {
        this.actualizadoEn = actualizadoEn;
    }
    public String getActualizadoPor() {
        return this.actualizadoPor;
    }
    
    public void setActualizadoPor(String actualizadoPor) {
        this.actualizadoPor = actualizadoPor;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public Set getPermisoUsuarios() {
        return this.permisoUsuarios;
    }
    
    public void setPermisoUsuarios(Set permisoUsuarios) {
        this.permisoUsuarios = permisoUsuarios;
    }




}


